version: '3'

services:
  web:
    container_name: digital-twins-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=file:/app/data/prod.db
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - digital_twins_db:/app/data
    # Run migrations before starting access to app not strictly necessary if handled elsewhere 
    # but good for standalone generic use
    command: >
      sh -c "npx prisma@6.7.0 db push --accept-data-loss && node server.js"

volumes:
  digital_twins_db:
