version: '3'

services:
  web:
    container_name: digital-twins-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=file:/app/db/prod.db
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      # Persist SQLite database
      - ./has_db:/app/db
    # Run migrations before starting access to app not strictly necessary if handled elsewhere 
    # but good for standalone generic use
    command: >
      sh -c "npx prisma migrate deploy && node server.js"
