version: '3'

services:
  web:
    container_name: digital-twins-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/data/prod.db
      - NEXT_PUBLIC_API_URL=https://digitaltwin.dttools.app
    volumes:
      - digital_twins_db:/app/prisma/data
    # Run migrations before starting access to app not strictly necessary if handled elsewhere 
    # but good for standalone generic use
    command: >
      sh -c "mkdir -p /app/prisma/data && chown -R nextjs:nodejs /app/prisma/data && chmod -R 777 /app/prisma/data && npx prisma@6.7.0 db push --accept-data-loss --skip-generate && npx prisma@6.7.0 db seed && node server.js"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.digitaltwin.rule=Host(`digitaltwin.dttools.app`)"
      - "traefik.http.routers.digitaltwin.entrypoints=https"
      - "traefik.http.routers.digitaltwin.tls.certresolver=letsencrypt"
    networks:
      - default
      - easypanel

volumes:
  digital_twins_db:


networks:
  easypanel:
    external: true
